enum CONSTANTS {
  MAIN_COLOR = "#0095DD",
  BALL_SIZE = 10,
  MOVEMENT_SPEED = 2,
  CANVAS_WIDTH = 480,
  CANVAS_HEIGHT = 320,
  PADDLE_HEIGHT = 10,
  PADDLE_WIDTH = 75,
}

export default CONSTANTS;
